package io.recruittrack.backend.jobs;

import io.recruittrack.backend.common.enums.*;
import io.recruittrack.backend.users.User;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLRestriction;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity for the 'jobs' table.
 * Schema: approved Phase 2 database design — frozen.
 *
 * Soft delete: @SQLRestriction ensures all standard queries exclude deleted jobs.
 *
 * req_id: generated by JobServiceImpl on create (format: RT-{YEAR}-{NNN}).
 *         Unique constraint enforced at the database level.
 *
 * published_at: set by the service when status transitions DRAFT → ACTIVE.
 * closing_date: LocalDate (DATE column, no time component).
 */
@Entity
@Table(name = "jobs")
@SQLRestriction("deleted_at IS NULL")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Job {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false, length = 255)
    private String title;

    @Column(length = 150)
    private String department;

    @Column(length = 255)
    private String location;

    @Enumerated(EnumType.STRING)
    @Column(name = "work_mode", length = 30)
    private WorkMode workMode;

    @Enumerated(EnumType.STRING)
    @Column(name = "job_type", length = 30)
    private JobType jobType;

    @Enumerated(EnumType.STRING)
    @Column(name = "seniority_level", length = 30)
    private SeniorityLevel seniorityLevel;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private JobStatus status = JobStatus.DRAFT;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(columnDefinition = "TEXT")
    private String requirements;

    @Column(columnDefinition = "TEXT")
    private String responsibilities;

    @Column(name = "salary_min", precision = 15, scale = 2)
    private BigDecimal salaryMin;

    @Column(name = "salary_max", precision = 15, scale = 2)
    private BigDecimal salaryMax;

    @Column(name = "salary_currency", length = 10)
    @Builder.Default
    private String salaryCurrency = "USD";

    @Column(nullable = false)
    @Builder.Default
    private Integer headcount = 1;

    /** Auto-generated unique job requisition ID. Format: RT-{YEAR}-{NNN}. */
    @Column(name = "req_id", unique = true, length = 30)
    private String reqId;

    // ─── Relationships ────────────────────────────────────────

    /**
     * The hiring manager responsible for this role.
     * Optional — a job may exist without an assigned hiring manager.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hiring_manager_id")
    private User hiringManager;

    /** The user who created this job posting. Always set on creation. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false, updatable = false)
    private User createdBy;

    // ─── Timestamps ───────────────────────────────────────────

    /** Set when the job first transitions from DRAFT to ACTIVE. */
    @Column(name = "published_at")
    private Instant publishedAt;

    /** The date after which no more applications are accepted. */
    @Column(name = "closing_date")
    private LocalDate closingDate;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    /** The admin who soft-deleted this job. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deleted_by")
    private User deletedBy;

    // ─── Lifecycle ────────────────────────────────────────────

    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        if (updatedAt == null) updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }
}
